title: ClearlyDefined
description: Helping FOSS projects be more successful through clearly defined project data.
show_downloads: false
git_branch: master/docs
logo_url: assets/images/logo.png
google_analytics: UA-115020668-3
theme: 
wiki_folder: wiki
use_github_wiki: false
use_prose_io: true
use_toc: false
# Select search_engine component from:
# - js: it uses a built in javascript component that uses generated sitemap_full.xml to search inside your wiki
# - github : it uses internal github repository search
# - google : it uses cse search bar, you need to configure google_cse_token
#
search_engine : "js"
google_cse_token: 
# (boolean) Enable/disable wiki page list in sidebar
show_wiki_pages: true
# (integer) Maximum number of wiki page to shown in sidebar
show_wiki_pages_limit: 10
# (boolean) Enable/disable blog feature
blog_feature: false
# (boolean) Enable/disable wiki posts list in sidebar (needs blog_feature enabled)
show_wiki_posts: true
# (integer) Maximum number of wiki posts to shown in sidebar
show_wiki_posts_limit: 10
# from jekyll (read jekyll doc)
paginate: 5
paginate_path: "/blog/page:num"
permalink: /blog/posts/:year/:month/:day/:title:output_ext
defaults:
 -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
 -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
 -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
 -
    scope:
      path: blog
    values:
      layout: "blog"
sass:
    style: compressed
plugins:
 - jekyll-feed
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-avatar
 - jemoji
 - jekyll-mentions

#
# INCLUDING HOOKS
# They are optional, change them only if you need
# Check wiki documentation to learn how they work
#

inc_before_toc : 
inc_after_toc : 
inc_before_content : 
inc_after_content : 
inc_before_footer : 
inc_after_footer : 
inc_before_head : 
inc_after_head : "clearlydefined/head.html"
inc_before_meta : 
inc_after_meta : 
inc_before_scripts : 
inc_after_scripts : 
inc_before_styles : 
inc_after_styles : 
inc_before_header : 
inc_after_header : 
inc_before_tail : 
inc_after_tail : 
inc_before_tools : 
inc_after_tools : 

inc_before_page_list : "clearlydefined/sidebar.html"
inc_after_page_list :
inc_before_post_list :
inc_after_post_list :

