title: ClearlyDefined
description: Helping FOSS projects be more successful through clearly defined project data.
show_downloads: false
git_branch: master/docs
logo_url: assets/images/logo.png
google_analytics: UA-115020668-3
theme: 
wiki_folder: wiki
use_github_wiki: false
use_prose_io: true
use_toc: false
google_cse_token: 
defaults:
 -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
 -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
sass:
    style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed

#
# INCLUDING HOOKS
# They are optional, change them only if you need
# Check wiki documentation to learn how they work
#

inc_before_toc : 
inc_after_toc : 
inc_before_content : 
inc_after_content : 
inc_before_footer : 
inc_after_footer : 
inc_before_head : 
inc_after_head : "clearlydefined/head.html"
inc_before_meta : 
inc_after_meta : 
inc_before_scripts : 
inc_after_scripts : 
inc_before_styles : 
inc_after_styles : 
inc_before_header : 
inc_after_header : "clearlydefined/sidebar.html"
inc_before_tail : 
inc_after_tail : 
inc_before_tools : 
inc_after_tools : 

